package com.municipalidad.licencias.appLicencias.viewforms;

import com.municipalidad.licencias.appLicencias.dto.LicenciaDTO;
import com.municipalidad.licencias.appLicencias.dto.TitularDTO;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;


public class LicenciaPDF extends javax.swing.JPanel implements Printable{

    /**
     * Creates new form LicenciaPDF
     */
    public LicenciaPDF() {
        initComponents();
  
    }

    public LicenciaPDF(TitularDTO titular, LicenciaDTO licencia) {
    initComponents();

        // Clases → unir todas en un string: "A, B, C"
        String clases = licencia.getClases().stream()
                .map(Object::toString)
                .collect(java.util.stream.Collectors.joining(", "));
        txtTipoLicencia.setText(clases);

        txtFechaVencimiento.setText(licencia.getFechaVencimiento()
                .format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy")));

        txtApellido.setText(titular.getApellido() + ", " + titular.getNombre());
        txtFechaNacimiento.setText(titular.getFechaNacimiento()
                .format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        txtDireccion.setText(titular.getDomicilio());
        txtLicencia.setText(titular.getDni().toString());

        txtGrupoSanguineo.setText(
                titular.getGrupoSanguineo() + " " + titular.getFactorSanguineo()
        );

        txtDonante.setText(titular.getEsDonante() ? "SI" : "NO");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        if (pageIndex > 0) return NO_SUCH_PAGE;
        Graphics2D g2d = (Graphics2D) graphics;
        double panelWidth = this.getWidth();
        double panelHeight = this.getHeight();
        double pageWidth = pageFormat.getImageableWidth();
        double pageHeight = pageFormat.getImageableHeight();
        double x = (pageWidth - panelWidth) / 2;
        double y = (pageHeight - panelHeight) / 2;
        g2d.translate(pageFormat.getImageableX() + x, pageFormat.getImageableY() + y);
        this.printAll(g2d);
        return PAGE_EXISTS;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFechaVencimiento = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDonante = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtFechaNacimiento = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtGrupoSanguineo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtLicencia = new javax.swing.JLabel();
        txtApellido = new javax.swing.JLabel();
        txtTipoLicencia = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFechaVencimiento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtFechaVencimiento.setText("12/03/2024");
        add(txtFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 200, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("SANTA FE - SANTA FE");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        txtDonante.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDonante.setText("SI");
        add(txtDonante, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 190, -1));

        jLabel11.setText("Grupo y factor sanguíneo");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Clases");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, -1));

        jSeparator2.setForeground(new java.awt.Color(51, 153, 255));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 490, 20));

        txtFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtFechaNacimiento.setText("02/09/2000");
        add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 200, -1));

        jLabel8.setText("Apellido y Nombre");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 110, -1));

        jLabel12.setText("Fecha de Vencimiento");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        txtDireccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDireccion.setText("Siempreviva 123");
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 200, 30));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 10, 40));

        txtGrupoSanguineo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtGrupoSanguineo.setText("O+");
        add(txtGrupoSanguineo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 80, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 153, 255));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 490, 20));

        jLabel17.setText("N° Licencia");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 70, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("VIAL");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/argentina (1).png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/escudo-de-armas (4).png"))); // NOI18N
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        jLabel14.setText("Domicilio");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 60, -1));

        txtLicencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtLicencia.setText("42765715");
        add(txtLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 100, -1));

        txtApellido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtApellido.setText("Servin");
        add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txtTipoLicencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTipoLicencia.setText("A1");
        add(txtTipoLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("SEGURIDAD");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 80, -1));

        jLabel9.setText("Donante");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("LICENCIA NACIONAL DE CONDUCIR");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel16.setText("Fecha de Nacimiento");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoAzul.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 490, 60));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel txtApellido;
    private javax.swing.JLabel txtDireccion;
    private javax.swing.JLabel txtDonante;
    private javax.swing.JLabel txtFechaNacimiento;
    private javax.swing.JLabel txtFechaVencimiento;
    private javax.swing.JLabel txtGrupoSanguineo;
    private javax.swing.JLabel txtLicencia;
    private javax.swing.JLabel txtTipoLicencia;
    // End of variables declaration//GEN-END:variables
}
