package com.municipalidad.licencias.appLicencias.viewforms;

import com.municipalidad.licencias.appLicencias.dto.ComprobanteDTO;
import com.municipalidad.licencias.appLicencias.dto.LicenciaDTO;
import com.municipalidad.licencias.appLicencias.dto.TitularDTO;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.time.format.DateTimeFormatter;
import java.util.stream.Collectors;

/**
 *
 * @author pabli
 */
public class PresupuestoPDF extends javax.swing.JPanel implements Printable{

    /**
     * Creates new form PresupuestoPDF
     */
    public PresupuestoPDF() {
        initComponents();
    }

    public PresupuestoPDF(TitularDTO titular, LicenciaDTO licencia, ComprobanteDTO comprobante) {
        initComponents();

        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        String clases = licencia.getClases().stream()
                .map(Object::toString)
                .collect(Collectors.joining(", "));

        txtTipoLicencia.setText(clases);
        txtFechaVencimiento.setText(licencia.getFechaVencimiento().format(fmt));
        txtFecha.setText(comprobante.getFecha().format(fmt));
        txtNumComprobante.setText(comprobante.getId().toString()); // ✅ número real
        txtApellido.setText(titular.getApellido() + ", " + titular.getNombre());
        txtFechaNacimiento.setText(titular.getFechaNacimiento().format(fmt));
        txtDireccion.setText(titular.getDomicilio());
        txtLicencia.setText(titular.getDni().toString());
        txtGrupoSanguineo.setText(titular.getGrupoSanguineo() + " " + titular.getFactorSanguineo());
        txtDonante.setText(titular.getEsDonante() ? "SI" : "NO");
        txtMonto.setText("$" + comprobante.getMonto());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        
         if (pageIndex > 0) {
            return NO_SUCH_PAGE;
        }
        Graphics2D g2d = (Graphics2D)graphics;
        g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
        this.printAll(graphics); // imprimir el JPanel completo
        return PAGE_EXISTS;
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtNumComprobante = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtLugar = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtTipoLicencia = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtFechaVencimiento1 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtGrupoSanguineo1 = new javax.swing.JLabel();
        txtLicencia = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        txtGrupoSanguineo = new javax.swing.JLabel();
        txtDonante = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtFechaVencimiento = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        txtFechaNacimiento = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(595, 842));
        setMinimumSize(new java.awt.Dimension(595, 542));
        setPreferredSize(new java.awt.Dimension(595, 842));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, 30));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("República Argentina");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 740, -1, -1));

        txtNumComprobante.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNumComprobante.setText("000001");
        add(txtNumComprobante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 630, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("COMPROBANTE");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Municipalidad de Santa Fe");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Lugar:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("N° de comprobante: ");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, -1, -1));

        txtLugar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLugar.setText("Distrito La Capital");
        add(txtLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, 20));

        txtFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFecha.setText("20/06/2024");
        add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Fecha:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Licencia clases:");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        txtTipoLicencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTipoLicencia.setText("A1");
        add(txtTipoLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Dirección:");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("DNI:");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setText("Concepto:");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, -1));

        txtFechaVencimiento1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFechaVencimiento1.setText("Licencia de conducir ");
        add(txtFechaVencimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 150, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel32.setText("Forma de Pago:");
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, 20));

        txtGrupoSanguineo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGrupoSanguineo1.setText("Débito");
        add(txtGrupoSanguineo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 80, -1));

        txtLicencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLicencia.setText("42765715");
        add(txtLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Apellido y nombre: ");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        txtApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApellido.setText("Servin");
        add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 620, 20));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Grupo Sanguíneo:");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, 20));

        txtGrupoSanguineo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGrupoSanguineo.setText("O+");
        add(txtGrupoSanguineo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 80, -1));

        txtDonante.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDonante.setText("SI");
        add(txtDonante, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 70, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Donante:");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, -1, -1));

        txtFechaVencimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFechaVencimiento.setText("12/03/2024");
        add(txtFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 100, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 620, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 620, 20));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setText("Fecha de Vencimiento:");
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));

        txtFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFechaNacimiento.setText("02/09/2000");
        add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 200, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setText("Fecha de nacimiento:");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        txtDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDireccion.setText("FALTA DIRECCION");
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, 40));

        jLabel26.setText("Comprobante válido para ser presentado en cualquier autoridad competente.");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 680, -1, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel34.setText("Monto:");
        add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, -1, -1));

        txtMonto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMonto.setText("$4800");
        add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, 70, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 620, 20));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 620, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel txtApellido;
    private javax.swing.JLabel txtDireccion;
    private javax.swing.JLabel txtDonante;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JLabel txtFechaNacimiento;
    private javax.swing.JLabel txtFechaVencimiento;
    private javax.swing.JLabel txtFechaVencimiento1;
    private javax.swing.JLabel txtGrupoSanguineo;
    private javax.swing.JLabel txtGrupoSanguineo1;
    private javax.swing.JLabel txtLicencia;
    private javax.swing.JLabel txtLugar;
    private javax.swing.JLabel txtMonto;
    private javax.swing.JLabel txtNumComprobante;
    private javax.swing.JLabel txtTipoLicencia;
    // End of variables declaration//GEN-END:variables
}
