/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.municipalidad.licencias.appLicencias.ui;

import com.municipalidad.licencias.appLicencias.model.Titular;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;

/**
 *
 * @author pabli
 */
public class Presupuesto extends javax.swing.JPanel implements Printable{

    /**
     * Creates new form Presupuesto
     */
    public Presupuesto() {
        initComponents();
        
    }
public Presupuesto(Titular titular, int Monto) {
        initComponents();
        txtApellido.setText(titular.getNombre());
        txtFechaNacimiento.setText(titular.getFechaNacimiento().toString());
        //txtDireccion.setText(titular.);
        txtLicencia.setText(titular.getDni().toString());
        txtTipoLicencia.setText(titular.getClass().toString());
        //txtFechaVencimiento.setText(titular.get);
        txtGrupoSanguineo.setText(Character.toString(titular.getGrupoSanguineo()));
        txtMonto.setText(String.valueOf(Monto));
        //txtNumTransaccion.setText();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumComprobante = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtHora = new javax.swing.JLabel();
        txtLugar = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtTipoLicencia = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtFechaVencimiento1 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtGrupoSanguineo1 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtNumTransaccion = new javax.swing.JLabel();
        txtLicencia = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        txtGrupoSanguineo = new javax.swing.JLabel();
        txtDonante = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtFechaVencimiento = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        txtFechaNacimiento = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(595, 842));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LICENCIA NACIONAL DE CONDUCIR");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/argentina (2).png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/escudo-de-armas (3).png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 70, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/escudo-de-armas (4).png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 720, 40, -1));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 720, 10, 40));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("SEGURIDAD");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 720, -1, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("VIAL");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 740, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ministerio de Transporte");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 720, -1, -1));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("República Argentina");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 740, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/argentina (1).png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 720, 60, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoAzul.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 600, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoAzul.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 80));

        txtNumComprobante.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNumComprobante.setText("000001");
        add(txtNumComprobante, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Comprobante de pago");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Municipalidad de Santa fe");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Lugar:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("N° de comprobante: ");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        txtHora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHora.setText("10:15");
        add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        txtLugar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLugar.setText("Santa fe");
        add(txtLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, 20));

        txtFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFecha.setText("20/06/2024");
        add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Fecha:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Hora: ");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Licencia clase:");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        txtTipoLicencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTipoLicencia.setText("A1");
        add(txtTipoLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Dirección:");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("DNI:");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setText("Concepto:");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, -1));

        txtFechaVencimiento1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFechaVencimiento1.setText("Licencia de conducir - renovacion");
        add(txtFechaVencimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 320, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel32.setText("Forma de pago:");
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, 20));

        txtGrupoSanguineo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGrupoSanguineo1.setText("Débito");
        add(txtGrupoSanguineo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 580, 80, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setText("N° de transaccion:");
        add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, -1, -1));

        txtNumTransaccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNumTransaccion.setText("1245");
        add(txtNumTransaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 640, 190, -1));

        txtLicencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLicencia.setText("42765715");
        add(txtLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Apellido y nombre: ");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        txtApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApellido.setText("BRAVO");
        add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 600, 20));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Grupo Sanguíneo:");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, 20));

        txtGrupoSanguineo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGrupoSanguineo.setText("O+");
        add(txtGrupoSanguineo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 80, -1));

        txtDonante.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDonante.setText("SI");
        add(txtDonante, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 190, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Donante:");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, -1, -1));

        txtFechaVencimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFechaVencimiento.setText("12/03/2024");
        add(txtFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 200, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 600, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 600, 20));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setText("Fecha de Vencimiento:");
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, -1, -1));

        txtFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFechaNacimiento.setText("02/09/2000");
        add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 200, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setText("Fecha de nacimiento:");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        txtDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDireccion.setText("HIPOLITO IRIGOYEN 1350 - CORONDA");
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, 40));

        jLabel26.setText("*Este comprobante es válido para ser presentado ante cualquier autoridad competente.");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 690, -1, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel34.setText("Monto:");
        add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, -1, -1));

        txtMonto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMonto.setText("$4800");
        add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 610, 190, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 600, 20));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 600, 20));
    }// </editor-fold>//GEN-END:initComponents
 @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        
         if (pageIndex > 0) {
            return NO_SUCH_PAGE;
        }
        Graphics2D g2d = (Graphics2D)graphics;
        g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
        this.printAll(graphics); // imprimir el JPanel completo
        return PAGE_EXISTS;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel txtApellido;
    private javax.swing.JLabel txtDireccion;
    private javax.swing.JLabel txtDonante;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JLabel txtFechaNacimiento;
    private javax.swing.JLabel txtFechaVencimiento;
    private javax.swing.JLabel txtFechaVencimiento1;
    private javax.swing.JLabel txtGrupoSanguineo;
    private javax.swing.JLabel txtGrupoSanguineo1;
    private javax.swing.JLabel txtHora;
    private javax.swing.JLabel txtLicencia;
    private javax.swing.JLabel txtLugar;
    private javax.swing.JLabel txtMonto;
    private javax.swing.JLabel txtNumComprobante;
    private javax.swing.JLabel txtNumTransaccion;
    private javax.swing.JLabel txtTipoLicencia;
    // End of variables declaration//GEN-END:variables
}
